#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  4 15:47:51 2017

@author: shawn
"""
import os

competition = 'House Prices _ Advanced Regression Techniques'
path = '/Users/shawn/Desktop/' + competition + '/'
os.chdir(path)
